/* Curated words for English, Russian, and Hebrew.
   Hebrew is pointed (nikud). Only words checked for spelling are included. */
(function (root) {
  var vocab = [
    { id: "cat", level: 1, topic: "animals", en: "cat", ru: "кошка", he: "חָתוּל" },
    { id: "dog", level: 1, topic: "animals", en: "dog", ru: "собака", he: "כֶּלֶב" },
    { id: "bird", level: 1, topic: "animals", en: "bird", ru: "птица", he: "צִפּוֹר" },
    { id: "fish", level: 1, topic: "animals", en: "fish", ru: "рыба", he: "דָּג" },
    { id: "cow", level: 1, topic: "animals", en: "cow", ru: "корова", he: "פָּרָה" },
    { id: "horse", level: 1, topic: "animals", en: "horse", ru: "лошадь", he: "סוּס" },
    { id: "lion", level: 1, topic: "animals", en: "lion", ru: "лев", he: "אַרְיֵה" },
    { id: "bear", level: 1, topic: "animals", en: "bear", ru: "медведь", he: "דֹּב" },
    { id: "sheep", level: 1, topic: "animals", en: "sheep", ru: "овца", he: "כִּבְשָׂה" },
    { id: "frog", level: 1, topic: "animals", en: "frog", ru: "лягушка", he: "צְפַרְדֵּעַ" },
    { id: "fox", level: 1, topic: "animals", en: "fox", ru: "лиса", he: "שׁוּעָל" },
    { id: "owl", level: 1, topic: "animals", en: "owl", ru: "сова", he: "יַנְשׁוּף" },
    { id: "duck", level: 1, topic: "animals", en: "duck", ru: "утка", he: "בַּרְוָז" },
    { id: "ant", level: 1, topic: "animals", en: "ant", ru: "муравей", he: "נְמָלָה" },
    { id: "bee", level: 1, topic: "animals", en: "bee", ru: "пчела", he: "דְּבוֹרָה" },
    { id: "monkey", level: 1, topic: "animals", en: "monkey", ru: "обезьяна", he: "קוֹף" },
    { id: "rabbit", level: 1, topic: "animals", en: "rabbit", ru: "кролик", he: "אַרְנָב" },
    { id: "mouse", level: 1, topic: "animals", en: "mouse", ru: "мышь", he: "עַכְבָּר" },
    { id: "chicken", level: 1, topic: "animals", en: "chicken", ru: "курица", he: "תַּרְנְגוֹלֶת" },
    { id: "donkey", level: 1, topic: "animals", en: "donkey", ru: "осёл", he: "חֲמוֹר" },
    { id: "camel", level: 1, topic: "animals", en: "camel", ru: "верблюд", he: "גָּמָל" },
    { id: "dove", level: 1, topic: "animals", en: "dove", ru: "голубь", he: "יוֹנָה" },

    { id: "red", level: 1, topic: "colors", en: "red", ru: "красный", he: "אָדֹם" },
    { id: "blue", level: 1, topic: "colors", en: "blue", ru: "синий", he: "כָּחֹל" },
    { id: "green", level: 1, topic: "colors", en: "green", ru: "зелёный", he: "יָרֹק" },
    { id: "yellow", level: 1, topic: "colors", en: "yellow", ru: "жёлтый", he: "צָהֹב" },
    { id: "white", level: 1, topic: "colors", en: "white", ru: "белый", he: "לָבָן" },
    { id: "black", level: 1, topic: "colors", en: "black", ru: "чёрный", he: "שָׁחֹר" },
    { id: "orange", level: 1, topic: "colors", en: "orange", ru: "оранжевый", he: "כָּתֹם" },
    { id: "pink", level: 1, topic: "colors", en: "pink", ru: "розовый", he: "וָרֹד" },
    { id: "purple", level: 1, topic: "colors", en: "purple", ru: "фиолетовый", he: "סָגֹל" },
    { id: "brown", level: 1, topic: "colors", en: "brown", ru: "коричневый", he: "חוּם" },

    { id: "one", level: 2, topic: "numbers", en: "one", ru: "один", he: "אַחַת" },
    { id: "two", level: 2, topic: "numbers", en: "two", ru: "два", he: "שְׁתַּיִם" },
    { id: "three", level: 2, topic: "numbers", en: "three", ru: "три", he: "שָׁלוֹשׁ" },
    { id: "four", level: 2, topic: "numbers", en: "four", ru: "четыре", he: "אַרְבַּע" },
    { id: "five", level: 2, topic: "numbers", en: "five", ru: "пять", he: "חָמֵשׁ" },
    { id: "six", level: 2, topic: "numbers", en: "six", ru: "шесть", he: "שֵׁשׁ" },
    { id: "seven", level: 2, topic: "numbers", en: "seven", ru: "семь", he: "שֶׁבַע" },
    { id: "eight", level: 2, topic: "numbers", en: "eight", ru: "восемь", he: "שְׁמוֹנֶה" },
    { id: "nine", level: 2, topic: "numbers", en: "nine", ru: "девять", he: "תֵּשַׁע" },
    { id: "ten", level: 2, topic: "numbers", en: "ten", ru: "десять", he: "עֶשֶׂר" },

    { id: "mom", level: 2, topic: "family", en: "mom", ru: "мама", he: "אִמָּא" },
    { id: "dad", level: 2, topic: "family", en: "dad", ru: "папа", he: "אַבָּא" },
    { id: "brother", level: 2, topic: "family", en: "brother", ru: "брат", he: "אָח" },
    { id: "sister", level: 2, topic: "family", en: "sister", ru: "сестра", he: "אָחוֹת" },
    { id: "grandma", level: 2, topic: "family", en: "grandma", ru: "бабушка", he: "סָבְתָא" },
    { id: "grandpa", level: 2, topic: "family", en: "grandpa", ru: "дедушка", he: "סָבָא" },
    { id: "baby", level: 2, topic: "family", en: "baby", ru: "малыш", he: "תִּינוֹק" },
    { id: "family", level: 2, topic: "family", en: "family", ru: "семья", he: "מִשְׁפָּחָה" },

    { id: "bread", level: 3, topic: "food", en: "bread", ru: "хлеб", he: "לֶחֶם" },
    { id: "water", level: 3, topic: "food", en: "water", ru: "вода", he: "מַיִם" },
    { id: "milk", level: 3, topic: "food", en: "milk", ru: "молоко", he: "חָלָב" },
    { id: "apple", level: 3, topic: "food", en: "apple", ru: "яблоко", he: "תַּפּוּחַ" },
    { id: "egg", level: 3, topic: "food", en: "egg", ru: "яйцо", he: "בֵּיצָה" },
    { id: "cheese", level: 3, topic: "food", en: "cheese", ru: "сыр", he: "גְּבִינָה" },
    { id: "soup", level: 3, topic: "food", en: "soup", ru: "суп", he: "מָרָק" },
    { id: "honey", level: 3, topic: "food", en: "honey", ru: "мёд", he: "דְּבַשׁ" },
    { id: "grapes", level: 3, topic: "food", en: "grapes", ru: "виноград", he: "עֲנָבִים" },
    { id: "cookie", level: 3, topic: "food", en: "cookie", ru: "печенье", he: "עוּגִיָּה" },
    { id: "banana", level: 3, topic: "food", en: "banana", ru: "банан", he: "בָּנָנָה" },

    { id: "book", level: 3, topic: "school", en: "book", ru: "книга", he: "סֵפֶר" },
    { id: "pen", level: 3, topic: "school", en: "pen", ru: "ручка", he: "עֵט" },
    { id: "pencil", level: 3, topic: "school", en: "pencil", ru: "карандаш", he: "עִפָּרוֹן" },
    { id: "school", level: 3, topic: "school", en: "school", ru: "школа", he: "בֵּית סֵפֶר" },
    { id: "teacher", level: 3, topic: "school", en: "teacher", ru: "учительница", he: "מוֹרָה" },
    { id: "friend", level: 3, topic: "school", en: "friend", ru: "друг", he: "חָבֵר" },
    { id: "table", level: 3, topic: "school", en: "table", ru: "стол", he: "שֻׁלְחָן" },

    { id: "shabbat", level: 4, topic: "jewish", en: "Shabbat", ru: "Шаббат", he: "שַׁבָּת" },
    { id: "torah", level: 4, topic: "jewish", en: "Torah", ru: "Тора", he: "תּוֹרָה" },
    { id: "challah", level: 4, topic: "jewish", en: "challah", ru: "хала", he: "חַלָּה" },
    { id: "chanukah", level: 4, topic: "jewish", en: "Chanukah", ru: "Ханука", he: "חֲנֻכָּה" },
    { id: "purim", level: 4, topic: "jewish", en: "Purim", ru: "Пурим", he: "פּוּרִים" },
    { id: "pesach", level: 4, topic: "jewish", en: "Pesach", ru: "Песах", he: "פֶּסַח" },
    { id: "matzah", level: 4, topic: "jewish", en: "matzah", ru: "маца", he: "מַצָּה" },
    { id: "sukkah", level: 4, topic: "jewish", en: "sukkah", ru: "сукка", he: "סֻכָּה" },
    { id: "lulav", level: 4, topic: "jewish", en: "lulav", ru: "лулав", he: "לוּלָב" },
    { id: "etrog", level: 4, topic: "jewish", en: "etrog", ru: "этрог", he: "אֶתְרוֹג" },
    { id: "shofar", level: 4, topic: "jewish", en: "shofar", ru: "шофар", he: "שׁוֹפָר" },
    { id: "rosh", level: 4, topic: "jewish", en: "Rosh Hashanah", ru: "Рош а-Шана", he: "רֹאשׁ הַשָּׁנָה" },
    { id: "kippur", level: 4, topic: "jewish", en: "Yom Kippur", ru: "Йом Кипур", he: "יוֹם כִּפּוּר" },
    { id: "shavuot", level: 4, topic: "jewish", en: "Shavuot", ru: "Шавуот", he: "שָׁבוּעוֹת" },
    { id: "dreidel", level: 4, topic: "jewish", en: "dreidel", ru: "волчок (дрейдл)", he: "סְבִיבוֹן" },
    { id: "kippah", level: 4, topic: "jewish", en: "kippah", ru: "кипа", he: "כִּפָּה" },
    { id: "candle", level: 4, topic: "jewish", en: "candle", ru: "свеча", he: "נֵר" },
    { id: "prayer", level: 4, topic: "jewish", en: "prayer", ru: "молитва", he: "תְּפִלָּה" },
    { id: "star", level: 4, topic: "jewish", en: "Star of David", ru: "Маген Давид", he: "מָגֵן דָּוִד" },
    { id: "synagogue", level: 4, topic: "jewish", en: "synagogue", ru: "синагога", he: "בֵּית כְּנֶסֶת" },
    { id: "rabbi", level: 4, topic: "jewish", en: "rabbi", ru: "раввин", he: "רַב" }
  ];

  root.BB_VOCAB = vocab;
  if (typeof module !== "undefined" && module.exports) module.exports = vocab;
})(typeof globalThis !== "undefined" ? globalThis : this);
